export const TABLE_HEADERS = [
    "RUC",
    "Código Proveedor",
    "Proveedor",
    "Código",
    "Tipo",
    "Marca",
    "Descripción",
    "Tipo de Conexión",
    "Potencia Máxima (KW)",
    "Número de MPPT",
    // "DoD (%)",
    // "Beta (%)",
    // "Arrays por MPPT",
    "Potencia AC (KW)",
    "VOC (V)",
    "VMPP (V)",
    "ISC (A)",
    "IMPP (A)",
    "Fuente eléctrica",
    "Fuente de divisas",
    "Precio S/.",
    "Precio $",
    "Precio S/. con IGV",
    "Precio $ con IGV",
    "Fecha creada",
    "Fecha actualizada",
    "Estado del equipo",
    "Fecha estimada de importación",
    "Acciones",
];