name: CI - Portal Tec General

on:
  pull_request:
  push:
    branches: [main]

jobs:
  verify:
    name: Lint & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instalar dependencias
        run: npm ci

      # - name: Lint (Next.js ESLint)
      #   working-directory: .
      #   run: npx next lint

      - name: Build
        run: npm run build